# Generated by Django 4.2.2 on 2023-07-03 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='highlight_image',
            field=models.ForeignKey(blank=True, help_text='Hightlight image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='highlight_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
