# Generated by Django 4.0.6 on 2022-09-10 06:57

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='general_information',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='intro',
            field=models.CharField(max_length=128),
        ),
    ]
