# Generated by Django 4.0.6 on 2022-09-09 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('formpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.formpage')),
                ('contact_email', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=12)),
                ('contact_address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('base.formpage',),
        ),
    ]
