# Generated by Django 4.2.2 on 2023-07-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_homepage_highlight_image_homepage_highlight_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='highlight_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
