# Generated by Django 4.2.2 on 2023-06-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_aboutpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageourwork',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
