# Generated by Django 4.0.6 on 2022-09-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='general_information',
            field=models.TextField(default='something'),
            preserve_default=False,
        ),
    ]
