# Generated by Django 4.0.6 on 2022-09-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_contactpage_general_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='general_information',
        ),
        migrations.AddField(
            model_name='formpage',
            name='general_information',
            field=models.TextField(default='general information'),
            preserve_default=False,
        ),
    ]
