# Generated by Django 4.2.2 on 2023-06-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_homepageourwork_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecollaborations',
            name='dark_background',
            field=models.BooleanField(default=False, help_text='Check this if the logo is light colored and needs a dark background color.'),
        ),
    ]
