# Generated by Django 4.2.2 on 2023-11-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='member',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
