# Generated by Django 4.2.2 on 2023-07-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_page',
            field=models.BooleanField(default=True, help_text='Generates a page at /team/<name> with details for the member.'),
        ),
    ]
