# Generated by Django 4.2.2 on 2023-11-28 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_member_options_member_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='This field is used for project ordering.'),
            preserve_default=False,
        ),
    ]
