# Generated by Django 4.2.2 on 2023-07-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_member_member_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
    ]
