# Generated by Django 4.2.2 on 2023-07-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_member_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='designation',
            field=models.CharField(blank=True, help_text="Ignore this field if 'category' is sufficient.", max_length=255, null=True),
        ),
    ]
