# Generated by Django 4.2.2 on 2023-07-01 17:03

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_member_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='about',
            field=wagtail.fields.RichTextField(default='something', help_text='About the member.'),
            preserve_default=False,
        ),
    ]
