# Generated by Django 4.2.2 on 2023-07-01 18:45

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_member_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercategory',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
