# Generated by Django 4.2.2 on 2023-06-29 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('content', '0005_patent_publication_researchpage_externalinventor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.collection', verbose_name='Image Gallery'),
        ),
    ]
