# Generated by Django 4.2.2 on 2023-06-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_projectpage_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='collection',
        ),
    ]
