# Generated by Django 4.2.2 on 2023-07-03 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_courseprogram_options_coursefaculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.member'),
        ),
    ]
