[tool.poetry]
name = "crais-pesu"
version = "0.1.0"
description = "Website for crais PESU"
authors = ["RohanJnr <rohanjnr44@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.6"
wagtail = "^3.0.1"

[tool.poetry.dev-dependencies]
python-dotenv = "^0.20.0"
flake8 = "^4.0.1"
flake8-annotations = "^2.9.0"
taskipy = "^1.10.2"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
