# Generated by Django 4.0.6 on 2022-08-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='sd', max_length=256),
            preserve_default=False,
        ),
    ]
