# Generated by Django 4.0.6 on 2022-10-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesindexpage',
            name='intro',
            field=models.CharField(max_length=255),
        ),
    ]
