# Generated by Django 4.0.6 on 2022-09-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membercategory',
            options={'ordering': ('name',), 'verbose_name': 'Member Category', 'verbose_name_plural': 'Member Categories'},
        ),
    ]
