# Generated by Django 4.0.6 on 2022-07-23 12:48

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerauthor',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.basemember'),
        ),
        migrations.AddField(
            model_name='centerauthor',
            name='model',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_authors', to='research.publication'),
        ),
    ]
