# Generated by Django 4.0.6 on 2022-10-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='link',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
    ]
