# Generated by Django 4.0.6 on 2022-07-23 14:12

from django.db import migrations, models
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('published', 'Published'), ('granted', 'Granted')], max_length=64)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_category',
            field=models.CharField(choices=[('conference', 'Conference'), ('journal', 'Journal')], max_length=64),
        ),
    ]
