# Generated by Django 4.0.6 on 2022-09-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patent',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('date',)},
        ),
    ]
