# Generated by Django 4.0.6 on 2022-08-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_patent_alter_publication_publication_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpage',
            name='intro',
            field=models.CharField(default='something', max_length=255),
            preserve_default=False,
        ),
    ]
