# Generated by Django 4.1.1 on 2022-10-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_patent_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patent',
            options={'ordering': ('date_filed',)},
        ),
        migrations.RenameField(
            model_name='patent',
            old_name='date',
            new_name='date_filed',
        ),
        migrations.AddField(
            model_name='patent',
            name='date_granted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
