# Generated by Django 4.1.1 on 2022-10-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_newspage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
