# Generated by Django 4.0.6 on 2022-08-10 15:59

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontributors',
            name='contributor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.basemember'),
        ),
        migrations.AddField(
            model_name='projectcontributors',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='projects.projectpage'),
        ),
    ]
