# Generated by Django 4.0.6 on 2022-08-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectindexpage',
            name='intro',
            field=models.CharField(max_length=255),
        ),
    ]
