# Generated by Django 4.1.1 on 2022-10-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectcategory',
            name='slug',
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
