# Generated by Django 4.1.1 on 2022-10-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_projectcategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
