# Generated by Django 4.0.6 on 2022-09-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtimelinenode',
            old_name='node',
            new_name='node_name',
        ),
        migrations.AddField(
            model_name='eventtimelinenode',
            name='node_description',
            field=models.TextField(default='Description'),
            preserve_default=False,
        ),
    ]
