# Generated by Django 4.0.6 on 2022-09-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_node_eventtimelinenode_node_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtimelinenode',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
