# Generated by Django 4.1.1 on 2022-10-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventtimelinenode_datetime_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='status',
        ),
    ]
