# Generated by Django 4.1.1 on 2022-10-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_eventpage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
