# Generated by Django 4.1.1 on 2022-10-17 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventpage_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='end_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event end date and time.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventpage',
            name='start_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event start date and time.'),
            preserve_default=False,
        ),
    ]
