name: Code Lint and Pre-Commit
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python and dependencies
        uses: HassanAbouelela/actions/setup-python@setup-python_v1.4.1
        with:
          install_args: "--only dev"
          python_version: '3.11'

      - name: Lint
        run: pre-commit run --all-files
